config/routes.rb
Weinevents::Application.routes.draw do
  root :to => 'events#index'
  resources :events do
    member do
      post :notify_friend
    end
  end
  resources :users
  resource :session
 
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/cities/:city_id' => 'events#city_index'
   resources :cities
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :events
end

app/models/cities_regions.rb
class CitiesRegions < ActiveRecord::Base
  belongs_to :city
  belongs_to :region
end

app/models/city.rb
# Cities are a pre-defined set of larger cities used to aggregate all events happening around these cities. An example for a city is Munich.

class City < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :regions
  has_and_belongs_to_many :events
  has_many :locations
  has_many :organizers
  
  # Used to create nice URLs for the city pages. 
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :regions
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :start_datetime, :presence => true
  validates :end_datetime, :presence => true

  belongs_to :status
  belongs_to :organizer
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :regions
  has_many :events_users
  has_many :users, :through => :events_users
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :cities
  
  #def owned_by?(owner)
  #  return false unless owner.is_a? User
  #  user == owner
  #end
  
  # Used to create nice URLs for the city pages. 
   def to_param
     "#{id}-#{name.parameterize}"
   end
   
   default_scope order('start_datetime')
   scope :current, lambda { |time| where('end_datetime < ?', Time.zone.now) }
   scope :where_city, lambda { where('event.city_id = city_id') }
end

app/models/events_locations.rb
class EventsLocations < ActiveRecord::Base
  belongs_to :event
  belongs_to :location
end

app/models/events_regions.rb
class EventsRegions < ActiveRecord::Base
  belongs_to :event
  belongs_to :region
end

app/models/events_tags.rb
class EventsTags < ActiveRecord::Base
  belongs_to :event
  belongs_to :tag
end

app/models/events_users.rb
class EventsUsers < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  belongs_to :role
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, :presence => true
  validates :street_1, :presence => true
  validates :addresscity, :presence => true
  validates :zip, :presence => true

  belongs_to :status
  belongs_to :city
  has_and_belongs_to_many :events
end

app/models/locations_users.rb
class LocationsUsers < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  belongs_to :role
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  validates :name, :presence => true
  validates :street_1, :presence => true
  validates :addresscity, :presence => true
  validates :zip, :presence => true

  belongs_to :status
  belongs_to :city
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  belongs_to :user
  belongs_to :status
  belongs_to :type
end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :events
  has_and_belongs_to_many :cities
  has_and_belongs_to_many :countries
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_many :events, :through => :events_users
  has_many :organizers, :through => :organizers_users
#  has_many :locations, :through => :LocationRole
  has_many :users,  :through => :events_users
  has_many :users, :through => :organizers_users
  has_many :users, :through => :locations_users
end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :name, :presence => true

  has_many :events
  has_many :organizers
  has_many :locations
  has_many :users
  has_many :profiles
  has_many :regions
  has_many :countries
  has_many :tags
  has_many :categories
  has_many :cities
  has_many :roles
  has_many :types
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :events
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  attr_accessor :password
  
  validates :email, :uniqueness => true, 
            :length => { :within =>  5..50 }, 
            :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }

  validates :password, :confirmation => true, 
            :length => { :within => 8..50 },
            :presence => true,
            :if => :password_required?

            
  belongs_to :status
  has_one :profile
  has_many :events_users
  has_many :events, :through => :events_users
  has_many :organizers, :through => :organizers_users

  before_save :encrypt_new_password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
  
  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end
    
    def password_required?
      hashed_password.blank? || password.present?
    end
    
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :notify_friend, :city_index]
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
  
  def city_index
    @events = Event.find_all_by_city_id(params[:city_id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
  
  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: t('events.create_success') }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: t('events.update_success.') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  
  def notify_friend
    @event = Event.find(params[:id])
    Notifier.email_friend(@event, params[:name], params[:email]).deliver
    redirect_to @event, notice: t('events.notify_friend_success')
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<%= div_for event do %>
  <h3>
    <%= link_to event.name, event%>
      <span class='actions'>
        <%= link_to "Edit", edit_event_path(event) %>
        <%= link_to "Delete", event, :confirm => t('general.are_you_sure'), :method => :delete %>
      </span>   
  </h3>

<p>
  <b>Description:</b>
  <%= simple_format @event.description %>
</p>

<p>
  <b>Start datetime:</b>
  <%= @event.start_datetime %>
</p>

<p>
  <b>End datetime:</b>
  <%= @event.end_datetime %>
</p>

<p>
  <b>Cost:</b>
  <%= @event.cost %>
</p>

<p>
  <b>Website:</b>
  <%= @event.website %>
</p>

<p>
  <b>Organizer:</b>
  <%= @event.organizer %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	 <%= f.label :name, t('events.city') %><br />
     <%= f.collection_select :city_ids, City.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :name, t('events.name') %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description, t('events.description') %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_datetime, t('events.start_datetime') %><br />
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime, t('events.end_datetime') %><br />
    <%= f.datetime_select :end_datetime %>
  </div>

  <div class="field">
    <%= f.label :tags, t('events.tags') %> <br />
    <% for tag in Tag.all %>
      <%= check_box_tag 'event[tag_ids][]', tag.id, @event.tag_ids.include?(tag.id), :id => dom_id(tag) %>
      <%= label_tag dom_id(tag), tag.name, :class => "check_box_label" %>
    <% end %>
  </div>  
  
  <div class="field">
    <%= f.label :cost, t('events.cost') %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :website, t('events.website') %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :organizer, t('events.organizer') %><br />
    <%= f.number_field :organizer_id %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f)%>
  </div>
<% end %>

app/views/events/_notify_friend.html.erb
<%= form_tag(notify_friend_event_path(@event), :id => 'notify_friend_form', :style => 'display:none') do %>
	<div class="field">
		<%= label_tag :name, t('general.your_name') %> <br />
		<%= text_field_tag :name %>
	</div>
	<div class="field">
		<%= label_tag :email, t('your_friends_email') %> <br />
		<%= text_field_tag :email %>
	</div>
	<div class="actions">
		<%= submit_tag t('general.send_mail') %> or
		<%= link_to t('general.cancel'), '#', :onclick => "$('#notify_friend_form').slideUp()" %>
	</div>
<% end %>

app/views/events/city_index.html.erb
<h1><%= t('events.listing_events') %></h1>

<% @events.each do |event| %>
	<%= event.start_datetime %>
	<%= link_to event.name, event %>
	<%= link_to t('general.edit'), edit_event_path(event) %>
	<%= link_to t('general.destroy'), event, confirm: t('general.are_you_sure'), method: :delete %>
<% end %>

<br />

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1><%= t('events.listing_events') %></h1>

<table>
  <tr>
    <th>Event</th>
    <th>Beginn</th>
    <th>Ende</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.start_datetime %></td>
    <td><%= event.end_datetime %></td>
    <td><%= link_to t('general.show'), event %></td>
    <td><%= link_to t('general.edit'), edit_event_path(event) %></td>
    <td><%= link_to t('general.destroy'), event, confirm: t('general.are_you_sure'), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= render @event %>

<%= link_to t('events.send_by_email'), '#', :onclick => "$('#notify_friend_form').slideDown()" %>
<%= render 'notify_friend' %>