config/routes.rb
Weinevents::Application.routes.draw do
  root :to => 'events#index'
  resources :events do
    member do
      post :notify_friend
    end
  end
  resources :users
  resource :session
 
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/cities/:city_id' => 'events#city_index'
   resources :cities
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :events
end

app/models/cities_regions.rb
class CitiesRegions < ActiveRecord::Base
  belongs_to :city
  belongs_to :region
end

app/models/city.rb
# Cities are a pre-defined set of larger cities used to aggregate all events happening around these cities. An example for a city is Munich.

class City < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :regions
  has_and_belongs_to_many :events
  has_many :locations
  has_many :organizers
  
  # Used to create nice URLs for the city pages. 
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :regions
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :start_datetime, :presence => true
  validates :end_datetime, :presence => true

  belongs_to :status
  belongs_to :organizer
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :regions
  has_many :events_users
  has_many :users, :through => :events_users
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :cities
  
  #def owned_by?(owner)
  #  return false unless owner.is_a? User
  #  user == owner
  #end
  
  # Used to create nice URLs for the city pages. 
   def to_param
     "#{id}-#{name.parameterize}"
   end
   
   default_scope order('start_datetime')
   scope :current, lambda { |time| where('end_datetime < ?', Time.zone.now) }
   scope :where_city, lambda { where('event.city_id = city_id') }
end

app/models/events_regions.rb
class EventsRegions < ActiveRecord::Base
  belongs_to :event
  belongs_to :region
end

app/models/events_tags.rb
class EventsTags < ActiveRecord::Base
  belongs_to :event
  belongs_to :tag
end

app/models/events_users.rb
class EventsUsers < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  belongs_to :role
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, :presence => true
  validates :street_1, :presence => true
  validates :addresscity, :presence => true
  validates :zip, :presence => true

  belongs_to :status
  belongs_to :city
  has_and_belongs_to_many :events
end

app/models/locations_users.rb
class LocationsUsers < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  belongs_to :role
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  validates :name, :presence => true
  validates :street_1, :presence => true
  validates :addresscity, :presence => true
  validates :zip, :presence => true

  belongs_to :status
  belongs_to :city
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  belongs_to :user
  belongs_to :status
  belongs_to :type
end

app/models/region.rb
class Region < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :events
  has_and_belongs_to_many :cities
  has_and_belongs_to_many :countries
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_many :events, :through => :events_users
  has_many :organizers, :through => :organizers_users
#  has_many :locations, :through => :LocationRole
  has_many :users,  :through => :events_users
  has_many :users, :through => :organizers_users
  has_many :users, :through => :locations_users
end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :name, :presence => true

  has_many :events
  has_many :organizers
  has_many :locations
  has_many :users
  has_many :profiles
  has_many :regions
  has_many :countries
  has_many :tags
  has_many :categories
  has_many :cities
  has_many :roles
  has_many :types
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true

  belongs_to :status
  has_and_belongs_to_many :events
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  attr_accessor :password
  
  validates :email, :uniqueness => true, 
            :length => { :within =>  5..50 }, 
            :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }

  validates :password, :confirmation => true, 
            :length => { :within => 8..50 },
            :presence => true,
            :if => :password_required?

            
  belongs_to :status
  has_one :profile
  has_many :events_users
  has_many :events, :through => :events_users
  has_many :organizers, :through => :organizers_users

  before_save :encrypt_new_password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
  
  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end
    
    def password_required?
      hashed_password.blank? || password.present?
    end
    
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weinevents | Weinproben, Weinfest und andere Weinveranstaltungen in Ihrer Stadt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="header">
	<h1><%= link_to "Home", root_path %></h1>
	<h1><%= link_to "Städte", cities_path %></h1>
	<div id="user_bar">
		<% if logged_in? %>
			<%= link_to "Neues Event", new_event_path %> | 
			<%= link_to "Passwort ändern", edit_user_path(current_user) %> |
			<%= link_to "Abmelden", logout_path %>
		<% else %>
			<%= link_to "Einloggen", login_path %>
			<%= link_to "Anmelden", new_user_path %>
		<% end %>
	</div>
</div>

<div id="main">
	<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
	<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
	<%= yield %>
</div>

<div id="footer">
</div>

</body>
</html>

app/views/notifier/email_friend.html.erb
<html> 
<body>
<p>
t('notifiers.email_friend.your_friend') <%= @sender_name %> t('notifiers.email_friend.suggests'):  
</p>

<p>	
<strong><%= @event.name %> </strong> <%= event_url(@event, :host => "localhost:3000") %>
</p>

<p>
t('general.greetings'), 
</p>

<p>
t('general.your_team')
</p>

</body>
</html>

app/views/notifier/email_friend.text.erb
t('notifiers.email_friend.your_friend') <%= @sender_name %> t('notifiers.email_friend.suggests'):  

<%= @event.name %> <%= event_url(@event, :host => "localhost:3000") %>

t('general.greetings'), 

t('general.your_team')